SNAKEMAKE_MODULE: "snakemake/8.16.0"
FASTP_MODULE: "fastp/0.23.4"
BOWTIE2_MODULE: "bowtie2/2.4.2"
SAMTOOLS_MODULE: "samtools/1.21"
SINGLEM_MODULE: "singlem/0.18.3"
MEGAHIT_MODULE: "megahit/1.2.9"
DIAMOND_MODULE: "diamond/2.1.9"
CHECKM2_MODULE: "checkm2/1.0.2"
METABAT2_MODULE: "metabat2/2.15"
MAXBIN2_MODULE: "maxbin2/2.2.7"
BINETTE_MODULE: "binette/1.0.5"
DREP_MODULE: "drep/3.4.0"
COVERM_MODULE: "coverm/0.7.0"
GTDBTK_MODULE: "gtdbtk/2.4.0"
PRODIGAL_MODULE: "prodigal/2.6.3"
