# Software
SNAKEMAKE_MODULE: "snakemake/8.25.3"
FASTP_MODULE: "fastp/0.23.4"
BOWTIE2_MODULE: "bowtie2/2.4.2"
SAMTOOLS_MODULE: "samtools/1.21"
SINGLEM_MODULE: "singlem/0.18.3"
MEGAHIT_MODULE: "megahit/1.2.9"
DIAMOND_MODULE: "diamond/2.1.11"
CHECKM2_MODULE: "checkm2/1.0.2"
METABAT2_MODULE: "metabat2/2.17"
MAXBIN2_MODULE: "maxbin2/2.2.7"
FRAGGENESCAN_MODULE: "fraggenescan/1.32"
BEDTOOLS_MODULE: "bedtools/2.31.0"
SEMIBIN2_MODULE: "semibin/2.1.0"
BINETTE_MODULE: "binette/1.0.5"
DREP_MODULE: "drep/3.4.0"
COVERM_MODULE: "coverm/0.7.0"
GTDBTK_MODULE: "gtdbtk/2.4.0"
PRODIGAL_MODULE: "pprodigal/1.0.1"
HMMER_MODULE: "hmmer/3.3.2"
MMSEQS2_MODULE: "mmseqs2/17.b804f"
EMAPPER_MODULE: "eggnog-mapper/2.1.12"
PATHWAYTOOLS_MODULE: "pathway-tools/27.0"
BLAST_MODULE: "blast/2.13.0"
M2M_MODULE: "metage2metabo/1.5.3"
SIGNALP_MODULE: "signalp/6h"
GATK_MODULE: "gatk/4.6.1.0"
SEQTK_MODULE: "seqtk/1.4"

# Annotation databases
CHECKM2_DB: "/maps/datasets/globe_databases/checkm2/20250215/CheckM2_database/uniref100.KO.1.dmnd"
GTDB_DB: "/datasets/globe_databases/gtdbtk_db/20241001"
KEGG_DB: "/projects/alberdilab/data/databases/drakkar/kofams"
CAZY_DB: "/projects/alberdilab/data/databases/drakkar/cazy"
AMR_DB: "/projects/alberdilab/data/databases/drakkar/amr"
PFAM_DB: "/projects/alberdilab/data/databases/drakkar/pfam"
VFDB_DB: "/projects/alberdilab/data/databases/drakkar/vfdb"
