executor: slurm
jobs: 100
latency-wait: 60
use-conda: false
rerun-incomplete: true
rerun-trigger: mtime
keep-going: true
retries: 3

default-resources:
    mem_mb: 8 * 1024
    runtime: 10 * 2 ** (attempt - 1)
max-threads: 8
