#!/usr/bin/env python3
"""Summarize basic metadata of the dereplicated genomes (MAGs).

Produces a table with one row per dereplicated genome, matching the genome
identifiers used in the counts and bases tables generated by CoverM.
"""

import argparse
import gzip
import re
from pathlib import Path

import pandas as pd


def normalize_genome_name(value):
    """Strip directories, compression and FASTA extensions from a genome name."""
    name = Path(str(value).strip()).name
    name = re.sub(r"\.gz$", "", name, flags=re.IGNORECASE)
    name = re.sub(r"\.(fa|fna|fasta)$", "", name, flags=re.IGNORECASE)
    return name


def open_fasta(path):
    if str(path).endswith(".gz"):
        return gzip.open(path, "rt", encoding="utf-8")
    return open(path, "r", encoding="utf-8")


def contig_stats(path):
    """Return contig lengths and GC/N base counts of a FASTA file."""
    lengths = []
    current = 0
    gc = 0
    at = 0
    with open_fasta(path) as handle:
        for line in handle:
            if line.startswith(">"):
                if current:
                    lengths.append(current)
                current = 0
                continue
            sequence = line.strip()
            current += len(sequence)
            upper = sequence.upper()
            gc += upper.count("G") + upper.count("C")
            at += upper.count("A") + upper.count("T")
    if current:
        lengths.append(current)
    return lengths, gc, at


def n50(lengths, total):
    half = total / 2
    cumulative = 0
    for length in sorted(lengths, reverse=True):
        cumulative += length
        if cumulative >= half:
            return length
    return 0


def load_quality(path):
    """Map genome id to (completeness, contamination) from the metadata CSV."""
    if not path:
        return {}
    metadata_path = Path(path)
    if not metadata_path.exists():
        return {}
    df = pd.read_csv(metadata_path)
    if "genome" not in df.columns:
        raise ValueError(f"Metadata file missing required 'genome' column: {metadata_path}")
    quality = {}
    for row in df.itertuples(index=False):
        values = row._asdict()
        quality[normalize_genome_name(values["genome"])] = (
            values.get("completeness", "NA"),
            values.get("contamination", "NA"),
        )
    return quality


def load_clusters(wdb_path, cdb_path):
    """Map genome id to (cluster, score, number of bins in the cluster)."""
    clusters = {}
    if not wdb_path or not Path(wdb_path).exists():
        return clusters

    wdb = pd.read_csv(wdb_path)
    if "genome" not in wdb.columns:
        raise ValueError(f"Wdb missing required 'genome' column: {wdb_path}")

    cluster_sizes = {}
    if cdb_path and Path(cdb_path).exists():
        cdb = pd.read_csv(cdb_path)
        if "secondary_cluster" in cdb.columns:
            cluster_sizes = cdb["secondary_cluster"].astype(str).value_counts().to_dict()

    for row in wdb.itertuples(index=False):
        values = row._asdict()
        cluster = str(values.get("cluster", "NA"))
        clusters[normalize_genome_name(values["genome"])] = (
            cluster,
            values.get("score", "NA"),
            cluster_sizes.get(cluster, "NA"),
        )
    return clusters


def build_table(genomes, quality, clusters):
    rows = []
    for genome_path in genomes:
        magid = normalize_genome_name(genome_path)
        lengths, gc, at = contig_stats(genome_path)
        size = sum(lengths)
        completeness, contamination = quality.get(magid, ("NA", "NA"))
        cluster, score, cluster_size = clusters.get(magid, ("NA", "NA", "NA"))
        rows.append(
            {
                "magid": magid,
                "completeness": completeness,
                "contamination": contamination,
                "size": size,
                "contigs": len(lengths),
                "longest_contig": max(lengths) if lengths else 0,
                "n50": n50(lengths, size),
                "gc": round(100 * gc / (gc + at), 2) if (gc + at) else "NA",
                "cluster": cluster,
                "cluster_members": cluster_size,
                "score": score,
            }
        )
    return pd.DataFrame(rows).sort_values("magid")


def main():
    parser = argparse.ArgumentParser(description="Summarize metadata of dereplicated genomes.")
    parser.add_argument("-g", "--genomes", required=True, nargs="+", help="Dereplicated genome FASTA files")
    parser.add_argument("-m", "--metadata", required=False, help="Path to genome quality metadata CSV")
    parser.add_argument("-w", "--wdb", required=False, help="Path to dRep Wdb.csv")
    parser.add_argument("-c", "--cdb", required=False, help="Path to dRep Cdb.csv")
    parser.add_argument("-o", "--output", required=True, help="Output TSV path")
    args = parser.parse_args()

    table = build_table(args.genomes, load_quality(args.metadata), load_clusters(args.wdb, args.cdb))

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    table.to_csv(output_path, sep="\t", index=False)


if __name__ == "__main__":
    main()
